### ISSUE TITLE
Windows setup doesn't create shortcut on Desktop and Start Menu

### ISSUE THREAD

**Issue by gluons** [egoist/devdocs-desktop#11]
I downloaded [`DevDocs.Setup.0.1.0.exe`](https://github.com/egoist/devdocs-app/releases/download/v0.1.0/DevDocs.Setup.0.1.0.exe) from [release](https://github.com/egoist/devdocs-app/releases/tag/v0.1.0).

After finish installation, **DevDocs** launched. 🆗 
But I try to find **DevDocs** shortcut on Desktop and Start Menu but there is no **DevDocs** shortcut. 😳
If I close **DevDocs**, I have to open it from `%LocalAppData%\DevDocs` next time. (Or manually create shortcut after install) 🙀

**Comment by egoist** [comment]
Yeah, I don't really know how the Windows installer generated by [electron-builder](https://github.com/electron-userland/electron-builder) works 😅

**Comment by Meadowcottage** [comment]
Updating [electron-builder](https://github.com/electron-userland/electron-builder) to use the NSIS installer should fix this issue 😛

**Comment by Positive07** [comment]
@Meadowcottage is right! use NSIS for Windows. Also electron-builder has auto-updates and a lot of great things, like automatic builds in Travis/CircleCI + AppVeyor

This could fix both this and #18 with just 2 scripts (Travis + AppVeyor) and updating dependencies.

**Comment by Positive07** [comment]
0.4.0 does create a shortcut in desktop and application menu

**Comment by gluons** [comment]
Yes. [0.4.0](https://github.com/egoist/devdocs-app/releases/tag/v0.4.0) create shortcut. It work. 🎉

**Comment by gluons** [comment]
Seem it actually fixed. Now closed. 🎉
