### ISSUE TITLE
Option to open external links with in-app browser

### ISSUE THREAD

**Issue by egoist** [egoist/devdocs-desktop#31]
i.e. create a BrowserWindow for loading external links.

**Comment by UchihaCFC** [comment]
@egoist this issue is finished?

**Comment by egoist** [comment]
Do you need this feature? I haven't seen a use case for this 😄

**Comment by UchihaCFC** [comment]
That was my question when see this issue, I forget this then 👍

**Comment by egoist** [comment]
So I'm closing this for now, thanks for reminding me anyways!
