### ISSUE TITLE
AppImage is downloaded instead of windows installer

### ISSUE THREAD

**Issue by cristijora** [egoist/devdocs-desktop#37]
1. Go to https://devdocs.egoistian.com/ from windows desktop
2. Download by clicking Download for Windows button
3. DevDocs-0.6.3-x86_64.AppImage is downloaded instead of windows installer DevDocs-Setup-0.6.3.exe

**Comment by egoist** [comment]
I'm not sure how userAgent looks like on windows, can you help with this? https://github.com/egoist/devdocs-www/blob/master/src/utils.js#L7

**Comment by cristijora** [comment]
`/Windows/.test(window.navigator.userAgent)` returns `true` in my case

**Comment by egoist** [comment]
Fixed.
