### ISSUE TITLE
[Ubuntu 17.04] Failure integrating DevDocs-Desktop with the system

### ISSUE THREAD

**Issue by Barbiero** [egoist/devdocs-desktop#39]
Hi, Just downloaded the latest release(0.6.4, AppImage), and when executing it will ask me if I want to integrate DevDocs with my system. However, when I accept it, the following error is printed:

> `/home/barbiero/.local/share/applications/appimagekit-devdocs.desktop: error: value "devel;" for key "Categories" in group "Desktop Entry" contains an unregistered value "devel"; values extending the format should start with "X-"
> Error on file "/tmp/.mount_McyF2u/devdocs.desktop": Failed to validate the created desktop file`

It might be something wrong with the AppImage build, so I switched to the .deb version as a workaround but I believe you might want to look into it. I'm interested in this in particular because the .AppImage is only 50MB in size while the .deb uses roughly 128MB(according to my /opt/DevDocs folder).

Thank you for your work.

**Comment by egoist** [comment]
Thanks for reporting, will look into it later.

**Comment by probonopd** [comment]
Let me know if you need help on this.

**Comment by egoist** [comment]
Hopefully it's fixed in https://github.com/egoist/devdocs-desktop/releases/tag/v0.6.5
