### ISSUE TITLE
[Windows]: Unable to input spaces in search bar.

### ISSUE THREAD

**Issue by hydrogan** [egoist/devdocs-desktop#40]
It seems that there is a hot key conflict and every time I tried to input spaces in the search bar, nothing is inputed and the page just scrolled down. Is there a way to fix this? thanks!

**Comment by egoist** [comment]
You mean this? https://github.com/Thibaut/devdocs/issues/78

**Comment by a1253278916** [comment]
Yes, and thank you very much!
