### ISSUE TITLE
Can you make it portable and work offline

### ISSUE THREAD

**Issue by anandisrocking007** [egoist/devdocs-desktop#42]
Hello sir i love your this app but it does not work offline when i portabalize it and use it in another computer without internet by default the official devdoc website has option to store offline but it gets stored somewhere in C:\Users\xxxx\AppData\Roaming\DevDocs so when i take it to another computer it need to download the data again can you make it be stored in the software folder.

Also if possible can you make a 32-bit version it can then run in any computer and also because it is a small app it won't make any difference.

**Comment by egoist** [comment]
I think the unpacked version is what you want? See the [download section](https://github.com/egoist/devdocs-desktop/releases/latest).

**Comment by anandisrocking007** [comment]
did you mean
https://github.com/egoist/devdocs-desktop/releases/download/v0.6.4/DevDocs-0.6.4-win.zip

have used that what i am trying to say is that to use this app offline you need to press install in the following webpage

http://devdocs.io/offline

but the data is stored in C:\Users\xxxx\AppData\Roaming\DevDocs (where xxx is the username of your login profile) so when i take that file which is in my pendrive to another computer then it needs internet to redownload the data thus it needs internet everytime.
You could use https://portableapps.com/development  to make it portable with that folder location

**Comment by egoist** [comment]
Here you go: https://github.com/egoist/devdocs-desktop/releases/tag/v0.6.5

**Comment by thorstenkampe** [comment]
I tried the "portable" version for Windows (`DevDocs-0.6.5.exe`). It still looks for the docsets in %APPDATA%. I think you are misunderstanding what "portable" means: being able to put the application on a flash drive and use it on another computer. For that the docsets folder would need to be configurable - preferably as a sub folder in the application directory.

**Comment by anandisrocking007** [comment]
I have already made this app portable hope this helps 
https://github.com/egoist/devdocs-desktop/issues/61

Only problem is that when you exit it the app minimizes to system tray thus you have to exit it there and then pull the usb

**Comment by TCB13** [comment]
The "portable" version is anything but portable. Even if I copy my AppData/DevDocs folder whenever I run it in a different machine all previous downloads and settings are gone.
