### ISSUE TITLE
Installer is not English

### ISSUE THREAD

**Issue by gluons** [egoist/devdocs-desktop#51]
Windows 10 Pro Version 1703 - 64 bits

<img width="371" alt="default" src="https://user-images.githubusercontent.com/4688092/31810730-0d6538d2-b5a7-11e7-8d72-1da378d1b0a2.PNG">

**Comment by egoist** [comment]
Hmm I don't know what's going on here 😂

**Comment by gluons** [comment]
[v0.6.7](https://github.com/egoist/devdocs-desktop/releases/tag/v0.6.7) installer is back to English. 🤔

<img width="370" alt="default" src="https://user-images.githubusercontent.com/4688092/31848818-5dadb14a-b663-11e7-9ac8-9666ba9c8eba.PNG">
