### ISSUE TITLE
Custom Css doesn't work

### ISSUE THREAD

**Issue by verdecchia** [egoist/devdocs-desktop#52]
I open the custom.css file with by editor by selection the "Custom CSS" menu item from "Preferences" menu voice. I save custom.css file and reload the devdocs-desktop app. Unfortunatly no custom css take effect. 

![image](https://user-images.githubusercontent.com/169332/31988669-29a80dae-b970-11e7-926c-ed7d9e6af179.png)

**Comment by egoist** [comment]
Try overriding default background-color by using `!important`

**Comment by verdecchia** [comment]
yes, you are right, with !important it works like a charm.
Thank you!

![image](https://user-images.githubusercontent.com/169332/32104273-fc6ca394-bb23-11e7-8696-218da9ce8f69.png)
