### ISSUE TITLE
editor plugins

### ISSUE THREAD

**Issue by benswift** [egoist/devdocs-desktop#54]
Is there a way to get a text editor (e.g. Emacs) to bring up the devdocs app based on the symbol at point? If there's a plugin API or something then I'd be open to the idea of writing/modifying an Emacs plugin (similar to [dash at point](https://github.com/stanaka/dash-at-point)).

**Comment by egoist** [comment]
I just added support for calling devdocs-desktop with `devdocs://search/keyword`, currently only on macOS:

```bash
open devdocs://search/js%20slice
```

**Comment by benswift** [comment]
Oh, that's super nice. Thanks. When will it land?

**Comment by egoist** [comment]
Released https://github.com/egoist/devdocs-desktop/releases/tag/v0.6.8

**Comment by ccakes** [comment]
Not an Emacs solution, but this is what I'm using in Vim (and now I've completely switched away from Dash)

```viml
function! DevDocs()
  let l:word = expand("<cword>")
  let l:cmd = "silent !open 'devdocs://search/" . &ft . " " . l:word . "'"

  exec l:cmd
endfunction

nnoremap <silent> <C-k> :call DevDocs()<CR>
```

**Comment by benswift** [comment]
Great, thanks. Here's an Emacs version:

```emacs-lisp
(require 'url)

(defun devdocs-lookup (language name)
  (interactive "slanguage: \nsname: ")
  (shell-command
   (format "open devdocs://search/%s"
           (url-hexify-string (concat language " " name)))))
```
You can close this one now, I guess.
