### ISSUE TITLE
enable to set an arbitrary global shortcut key

### ISSUE THREAD

**Issue by shuntaroy** [egoist/devdocs-desktop#56]
It would be great if we could set any favourite combination of keys as the global shortcut key.

I am using macOS and I found `command+shift+D` conflicts in many apps.
For my case, I would like to set `command+shift+control+option+D` (or `Hyper+D`) so that no apps conflict the shortcut.

Thank you for your nice work!

**Comment by froiss** [comment]
You can already accomplish that by editing `~/Library/Application Support/DevDocs/config.json` and setting the `shortcut.toggleApp` field to the [accelerator string](https://electronjs.org/docs/api/accelerator) of your new shortcut.
