### ISSUE TITLE
docs available offline

### ISSUE THREAD

**Issue by benswift** [egoist/devdocs-desktop#57]
Is there a way to download a bunch of docsets and make them available offline (i.e. on my laptop, but without an internet connection)? There are a couple of oblique references to this in the docs/issues, but I can't seem to do it. This is the only thing I really miss from Dash---if there was an offline mode I'd be a happy camper :)

I'm on macOS 10.13, using pre-release `v0.68`.

**Comment by davidsonsns** [comment]
in the menu next to the search has the option **Offline Data**.
Maybe that's what you're looking for.

**Comment by benswift** [comment]
Oh, whoops. Didn't see that one. Thanks.
