### ISSUE TITLE
npm run dist:mac not working according to README.md

### ISSUE THREAD

**Issue by znafets** [egoist/devdocs-desktop#60]
In the README one can find:
"
...
## Distribute

```bash
$ npm run dist:mac
$ npm run dist:linux
$ npm run dist:win
```
the attempt to create a MAC distribution file will yield:
```
$> npm run dist:mac
npm ERR! missing script: dist:mac
```
As I am pretty new to npm I wondered about the layout of the package.json file, as the dist prop attempts to invoke a build prop which is outside the scope of the script prop.

I am confused, and so it seems is npm.
```
$> npm -version
5.6.0
$> node --version
v9.3.0
```

**Comment by egoist** [comment]
Ah yeah, I gotta fix that, you can simply run `npm run dist` and it will automatically detect platform.

**Comment by znafets** [comment]
@egoist: you package.json layout is really compelling would be great if it could work like this
