### ISSUE TITLE
hide disabled category

### ISSUE THREAD

**Issue by pynixwang** [egoist/devdocs-desktop#63]
![image](https://user-images.githubusercontent.com/1189879/35092107-56a77fd2-fc79-11e7-8198-2423578b5c09.png)

this css works well, but class name not so clear. maybe rename to `.diabled_category`

**Comment by egoist** [comment]
This app actually loads https://devdocs.io in a webview 😅  so that's not under our control.

**Comment by pynixwang** [comment]
@egoist  sorry wrong place.
