### ISSUE TITLE
Add of Install way

### ISSUE THREAD

**Issue by mitixx** [egoist/devdocs-desktop#74]
Devdocs app can install from using 'homebrew-cask'.
https://github.com/caskroom/homebrew-cask/blob/04b43f2349a9d74f428e4757949c5ed41bffe876/Casks/devdocs.rb
Devdocs app at 'homebrew-cask' has registreted by other people.
But, Install way by 'homebrew-cask' doesn't written Install page(Release page) of Devdocs app.
I propose to add install way from 'homebrew-cask'.
```brew cask install devdocs```
That's maybe developers friendly.

**Comment by nielsbom** [comment]
Isn't this fixed by https://github.com/Homebrew/homebrew-cask/blob/master/Casks/devdocs.rb ?
