### ISSUE TITLE
Fresh install Ubuntu 18: Unsupported browser error

### ISSUE THREAD

**Issue by oscarr-reyes** [egoist/devdocs-desktop#85]
I just have installed Ubuntu 18 in my machine, i installed devdocs debian package after installing the latest chrome version but right when i run the app it shows the unsupported browser error 
![screenshot from 2018-10-09 02-33-05](https://user-images.githubusercontent.com/5789159/46653464-bd241d80-cb6b-11e8-8630-cc7d46c24188.png)

I've no idea what causes this, i used to have ubuntu 16.04 and devdocs was working in that version

**Comment by Alex131089** [comment]
Probably related to https://github.com/freeCodeCamp/devdocs/commit/847cfbb682c3bccdfe9e53c1d72a541787d1619f

**Comment by tobiasboyd** [comment]
Same w/ a homebrew cask install on macOS 10.13.6.

**Comment by hiredgunhouse** [comment]
Same with Ubuntu 16.04, it was fine until I clicked Reload page to refresh the content.

**Comment by hiredgunhouse** [comment]
Could this be fixed by updating to the latest Electron version?

**Comment by Thibaut** [comment]
Will deploy the fix in a few hours when I get home. Sorry for the disruption everyone.

PS: I'd recommend `devdocs-desktop` updates to the lastest version of Electron, as it's quite a few versions behind, and using a version of Chrome that's a year and a half old.

**Comment by Thibaut** [comment]
Never mind, fix is deployed :)

**Comment by oscarr-reyes** [comment]
I just checked and it's now working on my end, thanks for the fix.. i will close this issue now
